# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20170315_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes',
            old_name='conmes',
            new_name='topmes',
        ),
    ]
