# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20170315_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u72b6\u6001\u540d\u79f0')),
            ],
        ),
    ]
