# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_category_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.state'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u6807\u9898'),
        ),
    ]
