# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 06:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_auto_20170315_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='\u6587\u7ae0'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.ForeignKey(default='publication', on_delete=django.db.models.deletion.CASCADE, to='Model.State'),
        ),
    ]
