# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0017_auto_20170405_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.ForeignKey(default='publication', on_delete=django.db.models.deletion.CASCADE, to='Model.State'),
        ),
    ]
