# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:28
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('topic', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u6807\u9898')),
                ('digest', models.CharField(max_length=1000, verbose_name='\u6458\u8981')),
                ('toptime', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6587\u7ae0')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', DjangoUeditor.models.UEditorField(verbose_name='\u65e5\u5fd7\u5185\u5bb9')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='\u4fe1\u606f')),
                ('mestime', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('floor', models.IntegerField(default=1, verbose_name='\u697c\u5c42')),
                ('topmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u72b6\u6001\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.ForeignKey(default='publication', on_delete=django.db.models.deletion.CASCADE, to='Model.State'),
        ),
    ]
